### ISSUE TITLE
Koishi Desktop v0.3.x Roadmap

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi-desktop#45]
n = latest

## n+1 (≈ `v0.3.0`)

- [ ] 实现 `isolate` 配置项
- [ ] 实现 `koi export` 和 `koi import`（zip）
- [ ] 接入 boilerplate 并移除 `koi create`
- [x] #37

## n+2 (≈ `v0.4.0`)

- [ ] 将 `koi-build` 重构至支持 Platform Variant

## n+3 (≈ `v0.5.0`)

- [ ] 实现 `runner` 和 `ui` 配置项
- [ ] 支持 Tray

## n+4 (≈ `v0.6.0`)

- [ ] 开始设计 Platform Variant 支持，实现 WIX Installer

**Comment by ilharp** [comment]
由已过时之原因废弃。
